### ISSUE TITLE
Matrix Multiplication in cpp

### ISSUE THREAD

**Issue by PushkarMishra15** [Gaurang2908/HacktoberFest2022#112]
I want to add a  program of matrix multiplication in cpp.

**Comment by PushkarMishra15** [comment]
I would be glad if you would assign me this task

**Comment by Gaurang2908** [comment]
Hi @PushkarMishra15 ,
I have assigned this issue to you, you can create a PR for this now.

**Comment by Tesipog** [comment]
Hi @Gaurang2908 
I have Added Matrix Multiplication #116

**Comment by imNilabja** [comment]
I would like to do this task can you assign me

**Comment by Brainskull24** [comment]
Hey @Gaurang2908 Can you assign this task to me ?

**Comment by Gaurang2908** [comment]
Hi @Brainskull24,
You can also create a PR for this issue.
