### ISSUE TITLE
Performing Insertion, Deletion and Display options in a Linked List (using Menu Driven)

### ISSUE THREAD

**Issue by SS56Bo** [Gaurang2908/HacktoberFest2022#128]
As mentioned above, please assign me this problem

**Comment by Nehap-03** [comment]
Please assign me this problem

**Comment by imNilabja** [comment]
I would like to do this task can you assign me please.

**Comment by utkarshaskumbhar** [comment]
Please assign me this issue

**Comment by Gaurang2908** [comment]
Hi @SS56Bo , @Nehap-03 , @imNilabja , @utkarshaskumbhar,
I have assigned the issue to all of you, ya'll raise PRs.
