### ISSUE TITLE
C Program to Display Prime Numbers Between Intervals Using Function

### ISSUE THREAD

**Issue by Riyazmd786** [Gaurang2908/HacktoberFest2022#136]
can you please assign this to me

**Comment by imNilabja** [comment]
I would like to do this task can you assign me.

**Comment by utkarshaskumbhar** [comment]
Can you please assign me this issue

**Comment by Gaurang2908** [comment]
Hi @Riyazmd786 , @imNilabja , @utkarshaskumbhar ,
I have assigned the issue to all of you, ya'll raise PRs.
